# Generated by Django 2.0.8 on 2018-09-28 22:08

from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='start_time',
        ),
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.DurationField(default=timedelta(minutes=3)),
            preserve_default=False,
        ),
    ]
