# Generated by Django 2.0.8 on 2018-09-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tests', '0003_auto_20180928_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('cognitive', 'cognitive test'), ('skill', 'skill evaluation'), ('interview', 'structured interview')], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('type', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='useransweredquestion',
            unique_together={('question', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='usertest',
            unique_together={('test', 'user')},
        ),
    ]
